Fix really weird error in Linux g++ 4.3.2
With those lines, g++ outputs:

CC vm/llvm/inline.cpp
cc1plus: warnings being treated as errors
vm/inline_cache.hpp: In member function ‘bool
rubinius::Inliner::consider()’:
vm/inline_cache.hpp:48: error: array subscript is above array bounds
vm/inline_cache.hpp:40: error: array subscript is above array bounds

Which makes absolutely no sense. Removing these 2 lines does fix it
though. I think it's a bug in gcc.