Fixed assert using this for clang++ 6.1.0.
vm/oop.hpp:613:14: error: 'this' pointer cannot be null in
      well-defined C++ code; pointer may be assumed to always convert to true
      [-Werror,-Wundefined-bool-conversion]
      assert(this && (!reference_p() || (type_id() > InvalidType && type_id() < LastObje...
             ^~~~ ~~