Add missing rb_num_coerce_relop in 1.8 CAPI header
This suppresses the following warning from Clang:

  spec/ruby/optional/capi/ext/numeric_spec.c:77:10: warning:
    implicit declaration of function 'rb_num_coerce_relop' is invalid in C99
        [-Wimplicit-function-declaration]
    return rb_num_coerce_relop(x, y, SYM2ID(op));
           ^
  1 warning generated.