Fix Socket#new on X18
This fixes the following behaviour:

    require 'socket'

    # rbx -X18
    >> Socket.new(Socket::PF_UNIX, 'SOCK_DGRAM', 0)
    TypeError: converting to int

    >> Socket.new(Socket::PF_UNIX, :DGRAM, 0)
    TypeError: Tried to use non-reference value 0xf266 as type Bignum (10)

    # ruby1.8

    >> Socket.new(Socket::PF_UNIX, 'SOCK_DGRAM', 0)
    => #<Socket:0x106117798>

    >> Socket.new(Socket::PF_UNIX, :DGRAM, 0)
    Errno::EPROTONOSUPPORT: Protocol not supported - socket(2)